### PR TITLE
Add injectOptions to BlocklyDrawer's props

### PR DESCRIPTION
**Pull request by janezd**
I work on a project in which I need to have the toolbox on the right-hand side but the current implementation of `BlocklyDrawer` does not support additional arguments to `Blockly.inject`.

I added `injectOptions` to `this.props`, which are then passed to `inject`.

There's not much code, but please check carefully; I'm a newbie in react and javascript, and I can't be trusted. :)

### CODE REVIEW

**Comment by xvicmanx** [comment]
Hello Janez, thank you very much for the suggestions. I will definetly add that to the project. 
I would merge your PR but it modified the build folder not the src one. Could you make the PR again?
After making the modification you should also update/run the tests to make sure nothing breaks.
Thanks in advance.
I could also help you with that if you desired it.

**Comment by janezd** [comment]
I think I've fixed it and I even added a test.

I'm sorry, I'm a Python developer and I'm not used to `build` folders. :(
(Not entirely true; there's Cython, but nobody would even think about editing *those* built files.)

**Comment by xvicmanx** [comment]
Please do the changes to src folder files.

**Comment by janezd** [comment]
Hi, isn't this one OK? I had modified the commit so that it changes the src folder (and build files were changed in the process, not manually)?

**Comment by xvicmanx** [comment]
Oh my bad. I only saw the build files modified but not the src.

**Pull request merged**
